export const ActionTypes = {
  SET_LOADER: "SET_LOADER",
  AUTH: "AUTH",
  USERCHAT_LIST:"USERCHAT_LIST",
  SINGLE_CHAT:"SINGLE_CHAT",
  NOTIFICATIONS:"NOTIFICATIONS",
  SET_SHOW_CLICK:"SET_SHOW_CLICK",

};
